# Subscription: Listen for New CCTV Transact records
subscription SubscribeLatestCctv($session_id: uuid!, $site_id: uuid) {
  transact_cctv(
    where: {
      is_deleted: { _eq: false }
      session_id: { _eq: $session_id }
      site_id: { _eq: $site_id }
    }
    order_by: [{ updated_date: desc_nulls_last }, { created_date: desc }]
    limit: 1
  ) {
    id
    filename
    filepath
    is_active
    is_deleted
    created_by
    created_date
    updated_by
    updated_date
    site_id
    session_id
  }
}
