services:
  ftp-local:
    image: delfer/alpine-ftp-server:latest
    container_name: jtn-local-ftp
    restart: unless-stopped
    environment:
      USERS: "ftpuser|ftppass"
      ADDRESS: "127.0.0.1"
      MIN_PORT: "21100"
      MAX_PORT: "21110"
    ports:
      - "10021:21"
      - "21100-21110:21100-21110"
    volumes:
      - ./ftp-local-data:/home/ftpuser

