services:
  jtn-web:
    image: "taufansena/jtn-web:v20260616-amd64"
    platform: linux/amd64
    container_name: jtn-web-server
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_HASURA_URL: "http://51.79.173.213:8080/v1/graphql"
      NEXT_PUBLIC_HASURA_WS: "ws://hasura.activa.id/v1/graphql"
      NEXT_PUBLIC_HASURA_WS_IP: "ws://51.79.173.213:8080/v1/graphql"
      NEXT_PUBLIC_API_URL: "http://51.79.173.213:24000"
      NEXT_PUBLIC_SITE_ID: "e1123daf-a4db-4ee1-88da-ba9bff382f45"
      NEXT_PUBLIC_SITE_CODE: "MST-25-00001"
      NEXT_PUBLIC_SITE_NAME: "Mampang"
      NEXT_PUBLIC_SITE_LOCATION: "Central Office"
      NEXT_PUBLIC_SITE_REGION: "Default"
      NEXT_PUBLIC_MINIO_URL: "http://51.79.173.213:9000"
      NEXT_PUBLIC_DEVICE_CHECK_PROD_MODE: "false"
      NEXT_PUBLIC_DEVICE_CHECK_TIMEOUT_MS: "3000"
      NEXT_PUBLIC_ANPR_IP: "10.0.43.30"
      NEXT_PUBLIC_AXLE_IP: "10.0.43.40"
      NEXT_PUBLIC_CCTV_IP: "10.0.43.20"
      NEXT_PUBLIC_WIM_IP: "10.0.43.10"
    ports:
      - target: 3000
        published: 23000
        protocol: tcp
        mode: host

  jtn-api:
    image: "taufansena/jtn-api-service:v20260616-amd64"
    platform: linux/amd64
    container_name: jtn-api-server
    restart: unless-stopped
    environment:
      SERVICE: "api"
      SITE_ID: "e1123daf-a4db-4ee1-88da-ba9bff382f45"
      SITE_CODE: "MST-25-00001"
      SITE_NAME: "Mampang"
      SITE_LOCATION: "Central Office"
      SITE_REGION: "Default"
      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: "jatanlin-super-secret-jwt-key-2026"
      AUTH_ENABLED: "false"
      NATS_URL: "nats://51.79.173.213:4222"
      SESSION_WINDOW_SECONDS: "600"
      VEAM_PUBLIC_KEY_B64: "WnfI9zasq3U0eCV7dEkAYSNR2aNt9OLG+Gh0ttc0cQk="
      VEAM_LICENSE_PATH: "./data/license.veam"
      VEAM_HARDWARE_ID: ""
      API_PORT: "4000"
      ANPR_FTP_HOST: "10.0.43.100:10021"
      ANPR_FTP_USER: "ftpuser"
      ANPR_FTP_PASS: "ftppass"
      ANPR_FTP_DIR: "/ftp/ftpuser/anpr/"
      ANPR_FTP_INTERVAL_SEC: "5"
      AXLE_FTP_HOST: "10.0.43.100:10021"
      AXLE_FTP_USER: "ftpuser"
      AXLE_FTP_PASS: "ftppass"
      AXLE_FTP_DIR: "/ftp/ftpuser/axle/"
      AXLE_FTP_INTERVAL_SEC: "5"
      ANPR_MINIO_ENDPOINT: "51.79.173.213:9000"
      ANPR_MINIO_ACCESS_KEY: "admin"
      ANPR_MINIO_SECRET_KEY: "admin12345"
      ANPR_MINIO_BUCKET: "anpr"
      ANPR_MINIO_USE_SSL: "false"
      AXLE_MINIO_ENDPOINT: "51.79.173.213:9000"
      AXLE_MINIO_ACCESS_KEY: "admin"
      AXLE_MINIO_SECRET_KEY: "admin12345"
      AXLE_MINIO_BUCKET: "axle"
      AXLE_MINIO_USE_SSL: "false"
      ATTACHMENT_MINIO_ENDPOINT: "51.79.173.213:9000"
      ATTACHMENT_MINIO_ACCESS_KEY: "admin"
      ATTACHMENT_MINIO_SECRET_KEY: "admin12345"
      ATTACHMENT_MINIO_BUCKET: "attachment"
      ATTACHMENT_MINIO_USE_SSL: "false"
      DIMENSION_ENABLED: "true"
      DIMENSION_DUMMY_ENABLED: "true"
      WEIGHING_TRIGGER_URL: ""
      WEIGHING_TRIGGER_DIRECTION: "RIGHT"
      WEIGHING_TRIGGER_TIMEOUT_SECONDS: "60"
      WEIGHING_TRIGGER_SAVE: "true"
      WEIGHING_TRIGGER_DUMMY: "true"
      CCTV_TRIGGER_ENABLED: "true"
      CCTV_TRIGGER_URL: "http://51.79.173.213:26090/record"
      CCTV_TRIGGER_SECONDS: "20"
      CCTV_TRIGGER_DUMMY: "true"
    ports:
      - target: 4000
        published: 24000
        protocol: tcp
        mode: host
    volumes:
      - jtn-api-license-data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jtn-anpr:
    image: "taufansena/jtn-anpr-service:v20260616-amd64"
    platform: linux/amd64
    container_name: jtn-anpr-server
    restart: unless-stopped
    depends_on:
      - jtn-api
    environment:
      SERVICE: "anpr-watcher"
      SITE_ID: "e1123daf-a4db-4ee1-88da-ba9bff382f45"
      SITE_CODE: "MST-25-00001"
      SITE_NAME: "Mampang"
      SITE_LOCATION: "Central Office"
      SITE_REGION: "Default"
      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: "jatanlin-super-secret-jwt-key-2026"
      AUTH_ENABLED: "false"
      NATS_URL: "nats://51.79.173.213:4222"
      SESSION_WINDOW_SECONDS: "600"
      VEAM_PUBLIC_KEY_B64: "WnfI9zasq3U0eCV7dEkAYSNR2aNt9OLG+Gh0ttc0cQk="
      VEAM_LICENSE_PATH: "./data/license.veam"
      VEAM_HARDWARE_ID: ""
      ANPR_FTP_HOST: "10.0.43.100:10021"
      ANPR_FTP_USER: "ftpuser"
      ANPR_FTP_PASS: "ftppass"
      ANPR_FTP_DIR: "/ftp/ftpuser/anpr/"
      ANPR_FTP_INTERVAL_SEC: "5"
      ANPR_DUMMY_ENABLED: "true"
      ANPR_MINIO_ENDPOINT: "51.79.173.213:9000"
      ANPR_MINIO_ACCESS_KEY: "admin"
      ANPR_MINIO_SECRET_KEY: "admin12345"
      ANPR_MINIO_BUCKET: "anpr"
      ANPR_MINIO_USE_SSL: "false"
      AXLE_MINIO_ENDPOINT: "51.79.173.213:9000"
      AXLE_MINIO_ACCESS_KEY: "admin"
      AXLE_MINIO_SECRET_KEY: "admin12345"
      AXLE_MINIO_BUCKET: "axle"
      AXLE_MINIO_USE_SSL: "false"
      ATTACHMENT_MINIO_ENDPOINT: "51.79.173.213:9000"
      ATTACHMENT_MINIO_ACCESS_KEY: "admin"
      ATTACHMENT_MINIO_SECRET_KEY: "admin12345"
      ATTACHMENT_MINIO_BUCKET: "attachment"
      ATTACHMENT_MINIO_USE_SSL: "false"
      DIMENSION_ENABLED: "true"
      DIMENSION_DUMMY_ENABLED: "true"
      WEIGHING_TRIGGER_URL: ""
      WEIGHING_TRIGGER_DUMMY: "true"
      CCTV_TRIGGER_URL: "http://51.79.173.213:26090/record"
      CCTV_TRIGGER_DUMMY: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"


  jtn-axle:
    image: "taufansena/jtn-axle-service:v20260616-amd64"
    platform: linux/amd64
    container_name: jtn-axle-server
    restart: unless-stopped
    depends_on:
      - jtn-api
    environment:
      SERVICE: "axle-watcher"
      SITE_ID: "e1123daf-a4db-4ee1-88da-ba9bff382f45"
      SITE_CODE: "MST-25-00001"
      SITE_NAME: "Mampang"
      SITE_LOCATION: "Central Office"
      SITE_REGION: "Default"
      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: "jatanlin-super-secret-jwt-key-2026"
      AUTH_ENABLED: "false"
      NATS_URL: "nats://51.79.173.213:4222"
      SESSION_WINDOW_SECONDS: "600"
      VEAM_PUBLIC_KEY_B64: "WnfI9zasq3U0eCV7dEkAYSNR2aNt9OLG+Gh0ttc0cQk="
      VEAM_LICENSE_PATH: "./data/license.veam"
      VEAM_HARDWARE_ID: ""
      AXLE_FTP_HOST: "10.0.43.100:10021"
      AXLE_FTP_USER: "ftpuser"
      AXLE_FTP_PASS: "ftppass"
      AXLE_FTP_DIR: "/ftp/ftpuser/axle/"
      AXLE_FTP_INTERVAL_SEC: "5"
      AXLE_DUMMY_ENABLED: "true"
      ANPR_MINIO_ENDPOINT: "51.79.173.213:9000"
      ANPR_MINIO_ACCESS_KEY: "admin"
      ANPR_MINIO_SECRET_KEY: "admin12345"
      ANPR_MINIO_BUCKET: "anpr"
      ANPR_MINIO_USE_SSL: "false"
      AXLE_MINIO_ENDPOINT: "51.79.173.213:9000"
      AXLE_MINIO_ACCESS_KEY: "admin"
      AXLE_MINIO_SECRET_KEY: "admin12345"
      AXLE_MINIO_BUCKET: "axle"
      AXLE_MINIO_USE_SSL: "false"
      ATTACHMENT_MINIO_ENDPOINT: "51.79.173.213:9000"
      ATTACHMENT_MINIO_ACCESS_KEY: "admin"
      ATTACHMENT_MINIO_SECRET_KEY: "admin12345"
      ATTACHMENT_MINIO_BUCKET: "attachment"
      ATTACHMENT_MINIO_USE_SSL: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jtn-cctv:
    image: "taufansena/jtn-cctv-service:v20260616-amd64"
    platform: linux/amd64
    container_name: jtn-cctv-server
    restart: unless-stopped
    depends_on:
      - jtn-api
    environment:
      SERVICE: "cctv-streamer"
      SITE_ID: "e1123daf-a4db-4ee1-88da-ba9bff382f45"
      SITE_CODE: "MST-25-00001"
      SITE_NAME: "Mampang"
      SITE_LOCATION: "Central Office"
      SITE_REGION: "Default"
      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: "jatanlin-super-secret-jwt-key-2026"
      AUTH_ENABLED: "false"
      NATS_URL: "nats://51.79.173.213:4222"
      SESSION_WINDOW_SECONDS: "600"
      VEAM_PUBLIC_KEY_B64: "WnfI9zasq3U0eCV7dEkAYSNR2aNt9OLG+Gh0ttc0cQk="
      VEAM_LICENSE_PATH: "./data/license.veam"
      VEAM_HARDWARE_ID: ""
      ANPR_MINIO_ENDPOINT: "51.79.173.213:9000"
      ANPR_MINIO_ACCESS_KEY: "admin"
      ANPR_MINIO_SECRET_KEY: "admin12345"
      ANPR_MINIO_BUCKET: "anpr"
      ANPR_MINIO_USE_SSL: "false"
      AXLE_MINIO_ENDPOINT: "51.79.173.213:9000"
      AXLE_MINIO_ACCESS_KEY: "admin"
      AXLE_MINIO_SECRET_KEY: "admin12345"
      AXLE_MINIO_BUCKET: "axle"
      AXLE_MINIO_USE_SSL: "false"
      ATTACHMENT_MINIO_ENDPOINT: "51.79.173.213:9000"
      ATTACHMENT_MINIO_ACCESS_KEY: "admin"
      ATTACHMENT_MINIO_SECRET_KEY: "admin12345"
      ATTACHMENT_MINIO_BUCKET: "attachment"
      ATTACHMENT_MINIO_USE_SSL: "false"
      CCTV_MODE: "rtsp"
      CCTV_RTSP_URL: "rtsp://admin:P@ssw0rd@10.0.43.20:554/profile1"
      RTSP_URL: "rtsp://admin:P@ssw0rd@10.0.43.20:554/profile1"
      ONVIF_ENDPOINT: "http://10.0.43.20/onvif/device_service"
      ONVIF_USERNAME: "admin"
      ONVIF_PASSWORD: "P@ssw0rd"
      CCTV_TRIGGER_DUMMY: "true"
      CCTV_HTTP_PORT: "8090"
      PORT: "8090"
    ports:
      - target: 8090
        published: 26090
        protocol: tcp
        mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jtn-api-license-data:
