services:
  jtn-axle:
    image: taufansena/jtn-axle-service:latest
    container_name: jtn-axle-new
    restart: unless-stopped
    environment:
      SERVICE: axle-watcher
      SITE_CODE: MST-25-00001
      SITE_NAME: Mampang
      SITE_LOCATION: Central Office
      SITE_REGION: Default

      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: jatanlin-super-secret-jwt-key-2026
      NATS_URL: "nats://nats:natspass@51.79.173.213:4222"

      AXLE_FTP_HOST: "51.79.173.213:21"
      AXLE_FTP_USER: ftpuser
      AXLE_FTP_PASS: ftppass
      AXLE_FTP_DIR: /axle
      AXLE_FTP_INTERVAL_SEC: "5"
      AXLE_DUMMY_ENABLED: "true"

      AXLE_MINIO_ENDPOINT: "51.79.173.213:9000"
      AXLE_MINIO_ACCESS_KEY: minioadmin
      AXLE_MINIO_SECRET_KEY: minioadmin123
      AXLE_MINIO_BUCKET: axle
      AXLE_MINIO_USE_SSL: "false"
