services:
  jtn-cctv:
    image: taufansena/jtn-cctv-service:latest
    container_name: jtn-cctv-new
    restart: unless-stopped
    environment:
      SERVICE: cctv-streamer
      SITE_CODE: MST-25-00001
      SITE_NAME: Mampang
      SITE_LOCATION: Central Office
      SITE_REGION: Default

      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: jatanlin-super-secret-jwt-key-2026
      NATS_URL: "nats://nats:natspass@51.79.173.213:4222"

      RTSP_URL: rtsp://admin:admin@192.168.1.18:554/live.sdp
      CCTV_TRIGGER_DUMMY: "true"
      CCTV_HTTP_PORT: "8090"
      PORT: "8090"

      ATTACHMENT_MINIO_ENDPOINT: "51.79.173.213:9000"
      ATTACHMENT_MINIO_ACCESS_KEY: minioadmin
      ATTACHMENT_MINIO_SECRET_KEY: minioadmin123
      ATTACHMENT_MINIO_BUCKET: attachment
      ATTACHMENT_MINIO_USE_SSL: "false"
    ports:
      - target: 8090
        published: 26090
        protocol: tcp
        mode: host
