services:
  jtn-anpr:
    image: taufansena/jtn-anpr-service:latest
    container_name: jtn-anpr-new
    restart: unless-stopped
    environment:
      SERVICE: anpr-watcher
      SITE_CODE: MST-25-00001
      SITE_NAME: Mampang
      SITE_LOCATION: Central Office
      SITE_REGION: Default

      DATABASE_URL: "postgres://jatanlin:SuperSecretPasswordBang123@51.79.173.213:5432/jatanlin?sslmode=disable"
      JWT_SECRET: super-secret-jwt
      NATS_URL: "nats://nats:natspass@51.79.173.213:4222"

      ANPR_FTP_HOST: "51.79.173.213:21"
      ANPR_FTP_USER: ftpuser
      ANPR_FTP_PASS: ftppass
      ANPR_FTP_DIR: /ftp/ftpuser/anpr/
      ANPR_FTP_INTERVAL_SEC: "5"
      ANPR_DUMMY_ENABLED: "true"

      ANPR_MINIO_ENDPOINT: "51.79.173.213:9000"
      ANPR_MINIO_ACCESS_KEY: minioadmin
      ANPR_MINIO_SECRET_KEY: minioadmin123
      ANPR_MINIO_BUCKET: anpr
      ANPR_MINIO_USE_SSL: "false"

      AXLE_MINIO_ENDPOINT: "51.79.173.213:9000"
      AXLE_MINIO_ACCESS_KEY: minioadmin
      AXLE_MINIO_SECRET_KEY: minioadmin123
      AXLE_MINIO_BUCKET: axle
      AXLE_MINIO_USE_SSL: "false"

      ATTACHMENT_MINIO_ENDPOINT: "51.79.173.213:9000"
      ATTACHMENT_MINIO_ACCESS_KEY: minioadmin
      ATTACHMENT_MINIO_SECRET_KEY: minioadmin123
      ATTACHMENT_MINIO_BUCKET: attachment
      ATTACHMENT_MINIO_USE_SSL: "false"

      DIMENSION_ENABLED: "true"
      WEIGHING_TRIGGER_URL: "http://51.79.173.213:25000/ws/wim/anpr-capture"
      WEIGHING_TRIGGER_DUMMY: "true"
      CCTV_TRIGGER_URL: "http://51.79.173.213:26090/record"
      CCTV_TRIGGER_DUMMY: "true"
